### ISSUE TITLE
テスト規約について

### ISSUE THREAD

**Issue by HirokiTakenaka** [tantan5/codeBelle#2]
ひとまず最低限の内容で考えてみました。
コメントください！
### 全体
- 実装前に実装者がテスト設計を実施する（テスト駆動）
- プルリクエストレビュー者はテスト基準に従ったテストが実施済みであることを確認してからマージする（Travis CIを使用）
### 表示
- ページテンプレートが使用されている
- 文字化け、レイアウト崩れが無い
- POと合意した画面イメージに従っている
### ページ遷移
- トップページへのリンクが存在する
- リンク切れが無い
### 処理
- 正常系の操作を行った場合、期待通りの動作をし正常終了コードが返される
- 異常系の操作を行った場合、適切なエラーメッセージが表示される

**Comment by HirokiTakenaka** [comment]
ちなみに、OBはあまりテスト規約っぽいものは作ってないみたいで、
強いて言えばこれくらいでした。
https://github.com/KahokuHanten/oyaco/wiki/%E3%83%86%E3%82%B9%E3%83%88%E6%96%B9%E9%87%9D%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by akmura** [comment]
@HirokiTakenaka

## 自動化テスト

テスト自動化するスコープとしないスコープをはっきりさせた方が良いと思います。

昨日の議論では、静的ファイルについても最低限、HTTPステータスコードがOKであることは自動化で確認すべしとなっていたかと思います。
（逆に、elementを取得して、例えばページタイトルまで一致を確認するかについては、現時点では自動化の対象としない）

## POと合意した画面イメージ

これを入れる場合、ブランチの元となるIssueにおいて、POと合意した画面イメージが共有出来るようにホワイトボードに書いた画像をアップする等の対応をする運用をするといった事項を定めた方が良いと思います。
特に、レビューワーが何がテストベースになっているかが分からないので。

**Comment by akmura** [comment]
@HirokiTakenaka 
後、欲しいのは思いつく限り以下でしょうか。

### Issueとブランチ

No Issue、No Branch(Pull Request)という形で、Issueの作成はマスト
ブランチ名にルールを定めるかは悩みどころ。

### プルリクエスト名

日本語で、内容が容易に分かるように記載すること（容易の定義は、レビュワーが何に対する変更がすぐ分からなかったら差し戻すとかでしょうか）

### Merge

少なくとも1名のレビューは受けること（人数が少ないので、2名とすると、ちょっと運用回らなくなるリスクがある気がしますが、これは品質担保と生産性のトレードオフなので判断が必要でしょうか）

**Comment by tkhgsh** [comment]
異存はありません！ありがとうございます。ついて行きます。

**Comment by HirokiTakenaka** [comment]
コメントありがとうございます。

# 自動化テスト
- 各リンクの対象URLからのHTTPレスポンスコードがOKであること
- Ruby等で処理ロジックが記述されているものについて、
  　正常系、異常系のテストを実施する

# POと合意した画面イメージ
- 画面イメージに従う、または、プルリクの際にPOのレビューを受けること

# Issueとブランチ

# プルリクエスト名

# Merger
- 上記のとおり採用させて頂きます

コメント内容を含むよう修正し、Wikiに上げます

**Comment by HirokiTakenaka** [comment]
Wikiにテスト規約を載せました。
どなたか１名に内容確認してもらい、本Issueをクローズ願います。

**Comment by HirokiTakenaka** [comment]
進捗確認にてdone合意
