### ISSUE TITLE
コーディング規約について

### ISSUE THREAD

**Issue by HirokiTakenaka** [tantan5/codeBelle#4]
OBの例ですと、
下記のような感じみたいです。

ざっくり
https://github.com/tnumata3632/RakuTabi/wiki/Ruby%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84

しっかり（cookpad）
https://github.com/cookpad/styleguide/blob/master/ruby.ja.md

ざっくりの方を必須規約として、
しっかりの方は推奨程度の扱いでどうでしょうか。

**Comment by HirokiTakenaka** [comment]
wikiの方に載せましたので、そちらで内容確認願います。

**Comment by tkhgsh** [comment]
確認しました。ありがとうございます。

**Comment by HirokiTakenaka** [comment]
進捗確認にてdone合意
