### ISSUE TITLE
旅行画像の収集

### ISSUE THREAD

**Issue by tkhgsh** [tantan5/codeBelle#5]
# 対象地域

関東近辺１０箇所　（合意済み）
# 収集方法の計画

問題：　１．提案したい場所そのものの写真はフリーで使えない（許可の基準や手続きが明確でない）
　　　　　２．そのままでは面白くない

解決案：　とりあえずは場所を選ぶ
　　　　　　その場所のイメージに合った、フリー写真素材を探す

このような解決案でよいでしょうか？

**Comment by tkhgsh** [comment]
# 画像方針（決定）

画像はフリーライセンスのものだけ使用可能。明示されてないものは使えない。
そうすると、場所のそのものの写真はほぼ無い（許可が無い）ので、その紐付けは、イメージで
結果の表示については、イメージ自体は使わない。（では、リンクを表示とか？）

**Comment by tkhgsh** [comment]
# 目当ての場所

・目黒寄生虫館
・インスタントラーメン博物館
・ワープステーション江戸
・足尾銅山
・富岡製糸場
・巨大迷路パラディアム
・東京ドームシティ ASOBono！
・高尾山・薬王院
・将門神社
・泉岳寺・赤穂浪士の墓
・碓氷第三橋梁
・西多摩鍾乳洞
・コニカミノルタプラネタリウム
・釣船茶屋 ざうお
・犬吠埼
を選んでみました。　もしかすると、画像が合わずにけずらないといけないかもしれないので、１５カ所選んでます。
これからイメージを探します。

**Comment by tkhgsh** [comment]
見えました。ありがとうございます

**Comment by HirokiTakenaka** [comment]
本日の作業としては完了の認識でクローズします。
