### ISSUE TITLE
Resultsページの作成

### ISSUE THREAD

**Issue by HirokiTakenaka** [tantan5/codeBelle#9]
とりあえず着手します。

**Comment by HirokiTakenaka** [comment]
# ヘッダー　※テンプレート読み込み

### あなたにオススメの観光地は、
1. 高尾山
2. 東京タワー
3. 横浜

**Comment by HirokiTakenaka** [comment]
とりあえず最小限で上記のようなイメージで作成します。

**Comment by HirokiTakenaka** [comment]
ファイル名：results.html.erb

**Comment by HirokiTakenaka** [comment]
@tantan5 

### I/F仕様

　変数名：@dest_results1、@dest_results2、@dest_results3
　型　：文字列
　説明：出力する観光地名を格納

**Comment by tkhgsh** [comment]
👍
